version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: marketplace_postgres
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=marketplace_db
      - POSTGRES_USER=marketplace_user
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data: